### ISSUE TITLE
practica#4 calculadora

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-topicos4semestre2022#1]
[practica 3 sprint2.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-calculadora-en-consola-y-windows-form-topicos4semestre2022/files/8353380/practica.3.sprint2.pdf)

**Comment by Yareli-Perez** [comment]
calificación = 87 = 17.4%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
